name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: stable

      - name: Install dependencies
        run: forge install

      - name: Check contract sizes
        run: forge build --sizes

      - name: Run tests
        env: 
          POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
          AVALANCHE_RPC_URL: ${{ secrets.AVALANCHE_RPC_URL }}
        run: forge test -vvv
